### PR TITLE
proxy about.glitch.me and about-glitch.glitch.me -- case 3323312, case 3317554

### PR DESCRIPTION
**Pull request by judeallred**
https://glitch.manuscript.com/f/cases/3323312/Serve-about-and-legal-from-about-glitch-project

### CODE REVIEW

**Comment by judeallred** [comment]
live at https://navy-apartment.glitch.me/  https://navy-apartment.glitch.me/about https://navy-apartment.glitch.me/legal

n.b. '/about' won't show in prod until a cloudfront config change happens, but that can be handled separately from this deplyoment

**Comment by judeallred** [comment]
I'm expanding this to include case 3317554

**Comment by GregWeil** [comment]
It took me a bit to figure out `pathOnTarget` but that was mostly because I mixed up `about-glitch.glitch.me` and `about.glitch.me`.

Could you update the footer and team page to use relative urls instead of glitch.com/

**Comment by judeallred** [comment]
@GregWeil updated

**Comment by judeallred** [comment]
n.b. -- gareth mentioned that there's special redirect logic in the /FAQ/ redirect that's coded in about.glitch.me -- i need to make sure I didn't break that

**Comment by judeallred** [comment]
I'm going to sit on this until I return from XOXO

**Pull request merged**
