### PR TITLE
Understood basin: leave project popover

### PR DESCRIPTION
**Pull request by whimsicallyson**
## Links
* Remix link https://understood-basin.glitch.me
* Manuscript link https://glitch.manuscript.com/f/cases/3328669/Delete-collection-alert-dialog-doesn-t-match-delete-team-pop (related)

## GIF/Screenshots:
Screen Shot 2019-07-08 at 3 57 39 PM

## Changes:
* Uses `MultiPopover` to confirm you want to leave a project, instead of a system prompt

## How To Test:
* Leave a project that's part of a team you're in, you should leave without a popover.
* Leave a project that isn't, you should get a popover warning you about the consequences of leaving and asking if you're sure

## Things left to do before deploying:
- release the new homepage :)

### CODE REVIEW

**Comment by whimsicallyson** [comment]
@sarahzinger I'm not reproing? I did notice that after leaving a project from the search page, the popover stays open, so I fixed that.

**Comment by sarahzinger** [comment]
@whimsicallyson here's a screen recording: https://recordit.co/orNW0opM3V

how I create the bug:
- on @test-sarah I made a new project
- I invited @sarahzinger with the invite url from the editor (which redirects me to prod as @sarahzinger)
- I go back to your remix as @sarahzinger I then searched for the project on the search page
- I clicked the leave project button, in the console it tells me useTrackedFunc is not a function
- I refreshed the page and I'm still on the project,

**Comment by whimsicallyson** [comment]
@sarahzinger ok the issue was that "Leave Project" was showing up whether you had that permission or not. Fixed that :) 
In prod, you can't leave a project from the search page, so I'm comfortable keeping that (lack of) functionality.

**Comment by sarahzinger** [comment]
@whimsicallyson you can leave a project in prod from the search page :) https://recordit.co/769I7XZE9k

I have a fix for the permissions bug tho: https://github.com/FogCreek/Glitch-Community/pull/725

**Comment by sarahzinger** [comment]
lol I dunno, now I can't recreate this bug?? I'm going to say whatever I hit before is unrelated 🤷‍♀ 

let's shiiiip.

**Comment by whimsicallyson** [comment]
will do on monday! though it sounds like we might be reconsidering the "no deploys on fridays" rule :)

**Pull request merged**
