### PR TITLE
Identify glitch team members' profiles 

### PR DESCRIPTION
**Pull request by clottman**
## Links
* https://glitch-team-ids.glitch.me/@jennschiffer or any other team member's page (that's not you if you're logged in)
* https://github.com/FogCreek/Glitch-Community-Work/issues/470
* https://docs.google.com/document/d/1hBcVZZ1XiLvkOgEglGujOcU8CkUHDfKtbyGb3QrO1Ig/edit

## GIF/Screenshots:
image

image

## Changes:
* Adds a glitch icon that has a tooltip saying the person is a glitch team member, if the person is on the glitch team
* Does not add the glitch icon to the page of the logged in user, because presumably you know that you are on the glitch team already

## How To Test:
* Visit a staff member's glitch profile; visit a non-staff member's profile and make sure it doesn't show the glitch icon

## Feedback I'm looking for:
Anything!

### CODE REVIEW

**Comment by keithk** [comment]
Should we also do an audit on who is on the glitch team at the same time 👀

**Comment by ttseng** [comment]
This looks good to me.  The only thing I'd suggest changing is to change the emoji to the Glitch fish icon rather than the carpStreamer, so it's more obvious to users that the user is part of the Glitch team.  I'll put in a separate PR to add the Glitch emoji to the shared components library.

**Comment by ttseng** [comment]
PR for glitchLogo icon is here: https://github.com/FogCreek/shared-components/pull/52/files

**Comment by ttseng** [comment]
glitchLogo is now part of shared-components!

**Comment by clottman** [comment]
@ttseng has shared components been updated in the NPM registry? I see the last version was released 5 days ago. https://www.npmjs.com/package/@fogcreek/shared-components

**Comment by ttseng** [comment]
@clottman no sorry I actually don't know how to do that - I'll find out.

**Comment by ttseng** [comment]
@clottman changes should be on NPM now!

**Pull request merged**
