### PR TITLE
Change getDominantColor to match the api

### PR DESCRIPTION
**Pull request by GregWeil**
getDominantColor returns null if it finds any transparency in the image. That upsets the api which wants empty colors to be specified as an empty string.
I also did some very minor cleanup to make it more obvious what's happening

### CODE REVIEW

**Comment by ttseng** [comment]
@GregWeil From looking at how the user and team color / coverColor properties are used, it seems like they're used as CSS background-color attributes in the case that the uploaded avatar/cover images don't not load properly.  Is that right? 

I think it would be worth including a comment block before the function explaining what the function is used for, like we do for `resizeImage` and `drawCanvasThumbnail` in `assets.js`

**Comment by GregWeil** [comment]
Updated with a comment blob!

**Comment by ttseng** [comment]
functionally, `getDominantColor` is looking good to me.  However, when I actually go about testing it, it looks like the user's color attribute is not set as expected, but only for user avatars (cover images seem fine).

I tried uploading the following image as my avatar:

test

The correct dominant color is identified, but the user's color attribute is not updated.

**Comment by GregWeil** [comment]
It looks like the user's color field isn't writable, any changes just get ignored.

**Comment by ttseng** [comment]
ok - it looks to me like your changes can be merged, and we can let infrastructure know to make that field rewritable independently.

**Pull request merged**
