### PR TITLE
Projects css responsive and margins

### PR DESCRIPTION
**Pull request by PatrickWeaver**
Hello! Two very small fixes here, both in projects.styl:

The lists of projects on pages like [/community-picks](https://glitch.com/community-picks) currently break into a 2 column layout at 845px - 670px wide. This includes 768px iPad portrait width (where I first noticed it) so I would imagine it's somewhat common.

Fix is to change the pseudo class from `:last-child()` to `:nth-of-type(3n)` to remove the margin on the last column of projects.

I also changed the width property of these elements from `32%` to `calc(33% - 20px)` to take full advantage of the available width.

These changes are small so they might be easier to do live both are shown below:

```
  .projects-container
    margin: 0
    padding: 0
    list-style-type: none
    // overflow: auto
    overflow: hidden

    li
      
      float: left
      display: block
      margin-right: 10px
      width: calc(33% - 20px)      //  width: 32%
      position: relative
      margin-bottom: 12px
      @media (max-width: mediumViewport)
        width: 100%
        
    li:nth-of-type(3n)                  //  li:last-child
      margin-right: 0px
```

screen shot 2018-04-02 at 5 20 44 pm
screen shot 2018-04-02 at 5 20 52 pm

### CODE REVIEW

**Comment by pketh** [comment]
Hey Patrick, thanks for submitting our first PR 🎉

Changes look legit, I’ll look into merging later today

**Comment by jennschiffer** [comment]
hey @PatrickWeaver can you pull the latest master from origin into your branch, i want to see if that gets rid of the live site changes that were made before your commit

**Comment by jennschiffer** [comment]
happy first community pr 🎉

**Comment by pketh** [comment]
@PatrickWeaver i've added you as a pr contributor to https://support.glitch.com/t/glitch-credits , if you want a different name or link , @me and i'll update it

**Pull request merged**
