### PR TITLE
quilled-tilapia: improve project page description metadata

### PR DESCRIPTION
**Pull request by taravancil**
## Links
* [quilled-tilapia.glitch.me](https://quilled-tilapia.glitch.me)
* [Manuscript: Better project/team/user/collection page structured data](https://glitch.fogbugz.com/f/cases/3327826/Better-project-team-user-collection-page-structured-data)

## GIF/Screenshots:

**Projects that use the provided description**
Screen Shot 2019-05-29 at 11 37 22 AM

**Projects that use default text instead of the provided description**

Top to bottom:
1. no description
2. "A tidy project that does clean things"-style description
3. default description, remixed from one of our hello-* templates

sidebyside(7)

✅ ~🔜 These projects will eventually say something like, "_Check out ~tidy-project on Glitch, the friendly community..._" Need to confirm the exact copy with Ezra when he's back from vacation.~ 

## Changes:
- Detect if a project is using a default description, and use default text for metadata description if so
- Add `constants.tagline`, use it instead of 'Glitch is the friendly...' string literals

## How To Test:
Use [metatags.io](https://metatags.io) to test the following URLs:

You should see "Check out ~domain on Glitch, the friendly...":
- https://quilled-tilapia.glitch.me/~glory-guilt
- https://quilled-tilapia.glitch.me/~wonderful-kick
- https://quilled-tilapia.glitch.me/~hello-webpage

You should see "[Project description] 🎏 Glitch is the friendly...":
- https://quilled-tilapia.glitch.me/~culture-zine

## Feedback I'm looking for:
Is it broken in any way that I missed

## Things left to do before deploying:
- [x] Talk to Ezra about exactly what text we want to use
- [x] Confirm that we're cool using default project avatars when a project doesn't define an avatar

### CODE REVIEW

**Comment by ezramechaber** [comment]
This basically looks good to me, with one tweak.

For those with existing descriptions like `culture-zine`, let's do: _[Project description] Glitch is the friendly community where..._

(we might need to add a period or other character there to avoid a nonsensical sentence)

And for those that are missing or duplicating project descriptions, we could do: _Check out ~tidy-project on Glitch, the friendly community where..._

**Comment by taravancil** [comment]
A note about emoji in description metadata:

Twitter, FB, etc. will all display the 🎏 emoji in their cards. Googlebot is less consistent with emoji, and sometimes strips them if it finds the emoji to be spammy or irrelevant. We won't know if we'll get a pass until we deploy it 🤷🏻‍♀️

**Comment by sarahzinger** [comment]
looks good to me! 👍 should we strip out the ~ before projects? `Checkout glory-guilt on glitch` rather than `Checkout out ~glory-guilt on glitch` ?

**Comment by taravancil** [comment]
I _think_ we do want to include the "~", but if Ezra changes his mind later it's an easy fix!

**Pull request merged**
