### PR TITLE
fixing up add-project in prep for api changes -- case 3317561

### PR DESCRIPTION
**Pull request by judeallred**

### CODE REVIEW

**Comment by GregWeil** [comment]
The teamUsers and currentUserIsOnTeam props are both unused. Other than that, it looks good

**Comment by GregWeil** [comment]
I don't know what your remix is, so I couldn't test it out though

**Comment by judeallred** [comment]
@GregWeil ah, apologies!  it's here: https://staging.glitch.com/edit/#!/community    / aka staging.glitch.com

**Comment by judeallred** [comment]
currentUserIsOnTeam is in use in the 'add-team-project.jsx' file

**Comment by judeallred** [comment]
demo at https://staging.glitch.com/team-url

**Comment by pketh** [comment]
when i visit https://staging.glitch.com/team-url i get 401 errors and the page doesn't load. can you give me the glitch project url instead?

**Comment by judeallred** [comment]
community.staging.glitch.me

**Comment by judeallred** [comment]
merging this to unblock the api stuff;  all the UI choices and whatnot will continue iterating as parts of teams 2.0 though :-)

**Pull request merged**
