### PR TITLE
Ancient salmonberry: Convert Categories to Collections

### PR DESCRIPTION
**Pull request by sarahzinger**
UPDATE! this pr has changed a bunch since I wrote this description. This should now be a 1:1 replacement of categories to collections, and should hopefully not be noticeable to users

## Links
* Remix link: https://ancient-salmonberry.glitch.me/
* Issue-tracker link:
    - https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/528
    - https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/525
* Specs/doc links: https://docs.google.com/document/d/127bu23-WBPQmkFWMuFCYyc43wvtoYh_EokvLtRT3uQY/edit#

## GIF/Screenshots:
Screen Shot 2019-10-11 at 5 15 01 PM
Screen Shot 2019-10-11 at 5 15 26 PM

## Changes:
* All previous categories pages (ex: glitch.com/music) now use **collection** data instead of category data so that they are easier to manage by dev advocates. This will also fix an existing bug with Categories and My Stuff and help prevent future bugs with the new exploring collections project.
* Combines Art and Music into one category (since there is now going to be one collection for the two of them)
* Removes Learn to Code from the list

## How To Test:
* go to https://ancient-salmonberry.glitch.me/secret and enable the onboarding banners
* go to https://ancient-salmonberry.glitch.me/ and sign in with a new account that does not have any projects
* notice on the homepage that the onboarding banner has the new list of categories, make sure they all go to reasonable locations, try resizing the window to make sure it looks good
* notice on the user page that the onboarding banner has a new list of categories, make sure they also go to reasonable locations, try resizing the window to make sure it looks good
* go to the /create page and scroll to the bottom to the categories list and make sure they all go to reasonable locations, try resizing the window to make sure it looks good
* ensure that all old categories links go to an actively managed collection and it's not a dead link in case we have old tweets or youtubes referring to them:
    - https://ancient-salmonberry.glitch.me/hello-worlds
    - https://ancient-salmonberry.glitch.me/games
    - https://ancient-salmonberry.glitch.me/building-blocks
    - https://ancient-salmonberry.glitch.me/learn-to-code
    - https://ancient-salmonberry.glitch.me/tools-for-work
    - https://ancient-salmonberry.glitch.me/community-picks
    - https://ancient-salmonberry.glitch.me/handy-bots
    - https://ancient-salmonberry.glitch.me/hardware
    - https://ancient-salmonberry.glitch.me/art
    - https://ancient-salmonberry.glitch.me/music

## Feedback I'm looking for:
I'm probably missing something, what am i forgetting about? Can anyone think of something special categories give us that collections doesn't have? Is there any reason not to do this?

Stylistically a lot of these illustrations are not quite matching anymore, but they are not totally off? idk, I'm open to folks saying we need to pause this until we can get illustrations that best match what we're talking about.

## Things left to do before deploying:
- [ ] ideas is currently empty! let's have at least some stuff in there before we deploy this

### CODE REVIEW

**Comment by ttseng** [comment]
I'm not sure how to replicate this, but I quickly opened up all the links and got some 404s for some of the collections - the page URL is correct, but it looks like it may have been looking for it by name? 
image

**Comment by ttseng** [comment]
Based on discussion in #pod-exploring-collections, we are going to keep the original categories.  

From a UX perspective, I think it'll be important for:
1. the names to match (I should see the same name on /create as I do when I get redirected to the collection page)
2. the color of the collection should match
3. ideally, the avatar for the collection should match (on the link on /create and the collection page).  we *could* do it in a super hacky way and update the avatar URL manually, since technically it only shows the generated avatar if the collection's avatarUrl is the picture-frame default avatar:
```
const defaultAvatarName = 'collection-avatar'; // this was the old name for the default picture frame collection avatar
if (myStuffIsEnabled && collection.isMyStuff) {
    avatar = <BookmarkAvatar width="50%" />;
  } else if (collection.avatarUrl && !collection.avatarUrl.includes(defaultAvatarName)) {
    avatar = <Image src={collection.avatarUrl} alt="" />;
  } else if (collection.projects.length > 0) {
    avatar = <CollectionAvatar collection={collection} />;
  }
```
That's the only suggestion I can think of beyond adding new UI for users to upload their own avatar, which starts to feel like yak shaving.

**Comment by lyzidiamond** [comment]
Hello! I have made the requested changes and updated this PR:

- All URLs for collections now match URLs for categories 1:1 (except the two we removed during the homepage redesign, Hello Worlds and Community Picks)
- These are updated in `categories.js`
- Since we are moving back to 8 collections, I changed back `create.styl` to reflect that

Let me know if I need to do anything else here!

**Comment by modernserf** [comment]
I think for SEO purposes we should have `glitch.com/handy-bots` do a 301 redirect to `glitch.com/@glitch/bots`, instead of showing the same content at both URLs.

**Comment by ttseng** [comment]
looks like on the bottom of the search results page, "More Ideas" is not loading the correct content: 
image

**Comment by ttseng** [comment]
there was something wonky about the building-blocks avatar, so I replaced it directly in `ancient-salmonberry` (fixed version on right)
image

**Comment by sarahzinger** [comment]
cool I'm still actively working on this btw, I need to resolve merge conflicts and am exploring how redirects should work

**Comment by sarahzinger** [comment]
Ok y'all I think this is ready for another review if you don't mind! 

To summarize changes:
- all the category options are exactly as they were before
- however they now direct to glitch.com/@glitch/collection-name
- all previous links that might have been used in marketing (glitch.com/categoryName) will now redirect somewhere
- I also noticed that the color orange for the `Games` category wasn't consistent everywhere so I made it consistent
- I also noticed the name `Productivity` wasn't used consistently so I made that consistent. 
- One thing other change of note is that on these collection pages at the bottom it now shows more collections for the user to choose from instead of more collections. If this is undesirable let me know and I can edit the code so that it's how it was before!

**Pull request merged**
