### PR TITLE
🏬⭐️ raincoder-community — make `/careers` work

### PR DESCRIPTION
**Pull request by cori**
./server/proxy.js:242011/71

fixes https://fogcreek.slack.com/archives/C3U9U59NE/p1541710318041500 (mostly just stretching my legs). https://raincoder-community.glitch.me/careers/ in action.

### CODE REVIEW

**Comment by judeallred** [comment]
Sadly, it's bad mojo to have duplicate pages at https://raincoder-community.glitch.me/about/careers/ and https://raincoder-community.glitch.me/careers/ , would be better to redirect from one two the other if we need to support the pair.

because /about/careers/ is the cannonical url, we get some weirdness like this link will always point to the /about/careers/ location:
image


Before we take this approach, can we verify that we have to keep the canonical spot at /about/careers?  I believe Gareth made that original routing choice. If we could move it to /careers/ (and add a redirect from about/careers -> careers) that would get us to a better place in the long run.

**Comment by judeallred** [comment]
(unrelated to these changes;   Hi cori!  great to see your first PR!
  If it's helpful to you, here's the flow that we like to use: https://glitch.com/edit/#!/community?path=CONTRIBUTING.md:1:0

..but it's also perfectly to just send in PR's as they feel appropriate to you, like this one.  It probably deserved a better title that "🏬⭐️ Checkpoint #152" (we usually do a title like {remix-name} -- {feature description} ),  but other than that this is plenty clear :-)

)

**Comment by cori** [comment]
Updated to use a redirect instead of a proxy to maintain `/about/careers` as canonical.

**Comment by judeallred** [comment]
I think you did a great job here cori! I was calling out the doc because I didn't want to assume that you found it;  since you did, awesome

**Comment by cori** [comment]
ah perfect, thanks! It seemed like maybe I either went awry somewhere or the doc was out-of-date, and I wanted to make sure I understood it and was following the preferred process; since I've already pointed someone at the process I'd like to make sure I understand it.

**Pull request merged**
