### PR TITLE
Text - Text

### PR DESCRIPTION
**Pull request by oliviacpu**
Link to remix: https://faint-ptarmigan.glitch.me/

- [x] Created component
- [x] Added to storybook
- [x] In use in one location
- [ ] In use everywhere

💁 There are still places that have a class name set which I want to do in another PR.

### CODE REVIEW

**Comment by sarahzinger** [comment]
looks good to me! 🚢

**Comment by oliviacpu** [comment]
💛 Fixing merge conflicts.

**Comment by oliviacpu** [comment]
I think I messed this up.

**Comment by oliviacpu** [comment]
I think it's good actually.

**Pull request merged**
