### PR TITLE
Ivy scraper - Authentication Prototype

### PR DESCRIPTION
**Pull request by ttseng**
## Links
* Remix link: https://ivy-scraper.glitch.me/
* Manuscript link -
* Specs/Notion docs: https://www.notion.so/glitch/Authentication-UI-2c0a7259704b486f83c525e9ab33e1d6

## Changes:
- [x] Edited sign-in-pop to add user login with password
image

- [x] Added placeholder forgot password nested pop-overs
forgot-password
- [x] Added Account Settings Modal with error checking for whether password is too common (drawing from https://en.wikipedia.org/wiki/List_of_the_most_common_passwords#cite_note-splashdata2018-10), password + confirm password don't match, password is under 8 characters
- [x] Added simple custom password strength meter (checks if password has uppercase letters, includes a number, includes a special character to determine strength).  

strength-meter

Also disallows some common passwords (from https://en.wikipedia.org/wiki/List_of_the_most_common_passwords#cite_note-splashdata2018-10)
common-pw

(Outside of this remix, for mailer at https://cosmic-fossa.glitch.me/)
- [x] Added notice that user can change their password anytime under user settings https://cosmic-fossa.glitch.me/email-login
image
- [x] Added Reset Password mailer design https://cosmic-fossa.glitch.me/reset-password
image

## Known Bugs
* Account Settings modal only seems to open up on clicking the key icon (not the entire Account Settings button in the user-options-pop)

## Feedback I'm looking for:
* @GregWeil is there a way you'd prefer to consume this prototype so it'll be easier to connect to the API changes later?
* Is it bad to include passwords in state?

### CODE REVIEW

**Comment by GregWeil** [comment]
I think passwords in state is fine, if bad actors can access js values then they could access the dom and get the input value just as well.

I could just jump into this remix to wire stuff up, or if you merge the proto ui behind a switch I can wire it up in a separate branch. (I think we'll want the ui behind a switch at some point either way, the full spec would be a lot to merge all at once)

**Comment by ttseng** [comment]
sure - I'll add this behind a dev toggle

**Comment by ttseng** [comment]
Moved `User Passwords` behind a dev toggle. 

When you turn it on, you should see 
* email + password login in sign-in-pop
image

* account settings in user-options-pop when logged in
image

**Comment by oliviacpu** [comment]
`Account Settings modal only seems to open up on clicking the key icon (not the entire Account Settings button in the user-options-pop)`

I'm not seeing this, but I don't know if it was fixed or just a difference in browsers or something.

**Comment by sarahzinger** [comment]
hey hey, this has been around a while is it being used? should we close it?

**Comment by GregWeil** [comment]
I'm pretty sure all of this got pulled into the other password/2fa pr. I think it's safe to close.

**Comment by ttseng** [comment]
sure - this was . UI only prototype that has already been incorporated.

**Pull request closed without merging**
