### PR TITLE
Nova-chance: Remove dev toggles for team creation and deletion

### PR DESCRIPTION
**Pull request by GregWeil**
Are there any blockers here?

### CODE REVIEW

**Comment by pketh** [comment]
pinging this again, what are the remaining blockers?

**Comment by judeallred** [comment]
Blocker is that Anil wants to review the feature before we expose it in the header

**Comment by judeallred** [comment]
code wise, we're GTG.  We have some priority improvements but nothing that in my opinion blocks futher rollout

**Comment by pketh** [comment]
Would you like me to own getting Anil’s stamp on it?

**Comment by judeallred** [comment]
We're meeting tomorrow morning for a demo, so I don't know that there's anything to own.  This dragged out because he was out of town for so long.

**Pull request merged**
