### PR TITLE
Profuse tea: stricter email identification, more 404 handling, error boundaries

### PR DESCRIPTION
**Pull request by GregWeil**
- When adding a user to a team, don't consider the string to be an email domain unless it contains a . (`@greg` is not a domain, but `@gre.g` is)
- The create team pop didn't handle 404 errors from the api, now it does
- Added an `ErrorBoundary` component, which catches errors during rendering (not in event handlers or async stuff, only during rendering) and replaces its children with the standard 'something went wrong' text. It's used on the questions list (since it has had issue with bad data in the past) the page within `Layout`, and around the entire react tree. This should be enough such that users are never left with a completely blank page, and in most cases will still have a functional header

### CODE REVIEW

**Comment by GregWeil** [comment]
The easiest way to test without making a remix is probably to use the react debugger to inject bad state/props

**Comment by judeallred** [comment]
What's your assessment of ErrorBoundaries?  Were you able to break them with asynchrony, or do they seem fairly reliable?

**Comment by GregWeil** [comment]
Error boundaries don't catch async errors at all, but async errors also don't cause the page to white out (that only happens when there's an error in a render function or a constructor) I wasn't able to get the page to white out like this, though

**Comment by judeallred** [comment]
nice

**Pull request merged**
