### PR TITLE
remove use of user.email in favor of user.emails, case 3323347

### PR DESCRIPTION
**Pull request by judeallred**
./src/presenters/current-user.jsx:8/82

### CODE REVIEW

**Comment by judeallred** [comment]
This is the only spot I noticed where user.email was in play;  user.emails seems to be in use everywhere else.

**Comment by GregWeil** [comment]
`user.emails.find((email) => email.primary)` is slightly cleaner, but not a big difference

**Comment by judeallred** [comment]
ah, good call-- will fix

**Comment by judeallred** [comment]
thanks, fixed...  also i wasn't properly unboxing email before, so fixed that too.

**Pull request merged**
