### PR TITLE
Somber crane

### PR DESCRIPTION
**Pull request by judeallred**

### CODE REVIEW

**Comment by judeallred** [comment]
@etamponi created a PR so i could review the diff :-)

**Comment by judeallred** [comment]
I added a couple touchup commits, see above @etamponi

**Comment by judeallred** [comment]
In this branch, i see a bunch of users who have generic avatars now.

Is that a bug, or are these users who aren't backfilled, or something else?

image

**Comment by etamponi** [comment]
I backfilled another 1000 avatars :) We should be good to go with this change now.

**Comment by judeallred** [comment]
case 3302440 -- editable profile avatars!  paired with emanuele

**Pull request merged**
