### PR TITLE
Add hello-sqlite to starter apps

### PR DESCRIPTION
**Pull request by jennschiffer**
on desktop (mac ff): 

screenshot 2018-03-22 15 44 08

on mobile (ios safari):

img_7953

### CODE REVIEW

**Comment by pketh** [comment]
can you move sqlite to the second position? The reasoning being that the easiest one (website) should go last because for inexperienced users it’s like the ‘ok’ button in a dialog box

**Comment by judeallred** [comment]
I think that sounds like a good idea

**Comment by jennschiffer** [comment]
@pketh rearranged!

**Comment by judeallred** [comment]
sweet. shipit.

**Pull request merged**
