### PR TITLE
Jasper reward: React.memo Markdown component

### PR DESCRIPTION
**Pull request by modernserf**
## Links
* Remix link: https://jasper-reward.glitch.me/
* Issue-tracker link: https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/398

## Changes:
* wrap Markdown component in React.memo

## How To Test:
* visit https://jasper-reward.glitch.me/@developit
* click `Show all [45]` on recent projects
* it should display all recent projects
* your computer should not attempt liftoff

### CODE REVIEW

**Comment by clottman** [comment]
How do we know this is helping? It looks like it makes pressing the show all button take over a second more scripting time. Do we have some other data showing that it's helping with perf in a different way that justifies the extra time?

Jasper-reward: 
image

Curvy-bandicoot: (a fairly recent remix of community, that is also running in development mode)
image

glitch.com: (production mode)
image

**Comment by modernserf** [comment]
I have no idea how to reproduce the issue that Jason is experiencing here: https://twitter.com/_developit/status/1170016065373528071 -- we could tag him into this thread?

**Comment by taravancil** [comment]
I can't reproduce it either, but [Potch saw this](https://fogcreek.slack.com/archives/CB4EHAJ2J/p1565726918307100) about a month ago. I'll ask him if he can reprooduce.

**Comment by taravancil** [comment]
I approved this because it's noticeably broken - two folks have reported this internally and we know of at least one user who's seen it too. It's qualitatively broken, and even if there is a cost to memoizing, I think it's worth the "Show all" button not being busted.

**Pull request merged**
